- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
    - 1
  monitored_conditions:
    - icon
    - temperature
    - apparent_temperature
    - humidity
    - precip_probability
    - precip_intensity
    - precip_type
    - pressure
    - wind_speed
    - wind_bearing
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - daily_summary
  scan_interval:
      # At least one of these must be specified:
      days: 0
      hours: 4
      minutes: 0
      seconds: 0
      milliseconds: 0
      
- platform: template
  sensors:
    solar_elevation:
      friendly_name: "Sun Position"
      unit_of_measurement: '°'
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      
- platform: dewpoint
  sensors:
    dewpoint_outside:
      temperature: sensor.temperature_outside
      rel_hum: sensor.temperature_outside_2
    dewpoint_home:
      temperature: sensor.sensibo_living_room_temperature
      rel_hum: sensor.sensibo_living_room_humidity