# Aviv - PC
- platform: mqtt
  name: "AvivPC - HDD Usage (C)"
  state_topic: "iotlink/workgroup/aviv-pc/windows-monitor/stats/hard-drive/c/drive-usage"
  unit_of_measurement: '%'
  icon: mdi:chart-donut
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/aviv-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "AvivPC - HDD Usage (D)"
  state_topic: "iotlink/workgroup/aviv-pc/windows-monitor/stats/hard-drive/d/drive-usage"
  unit_of_measurement: '%'
  icon: mdi:chart-donut
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/aviv-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "AvivPC - CPU Usage"
  state_topic: "iotlink/workgroup/aviv-pc/windows-monitor/stats/cpu/usage"
  unit_of_measurement: '%'
  icon: mdi:speedometer
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/aviv-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "AvivPC - RAM Usage"
  state_topic: "iotlink/workgroup/aviv-pc/windows-monitor/stats/memory/usage"
  unit_of_measurement: '%'
  icon: mdi:memory
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/aviv-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
  
- platform: mqtt
  name: "AvivPC - Network IPv4"
  state_topic: "iotlink/workgroup/aviv-pc/windows-monitor/stats/network/0/ipv4"
  unit_of_measurement: ''
  icon: mdi:lan
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/aviv-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
  
- platform: mqtt
  name: "AvivPC - Network IPv6"
  state_topic: "iotlink/workgroup/aviv-pc/windows-monitor/stats/network/0/ipv6"
  unit_of_measurement: ''
  icon: mdi:lan
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/aviv-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
  
- platform: mqtt
  name: "AvivPC - Up Time"
  state_topic: "iotlink/workgroup/aviv-pc/windows-monitor/stats/system/uptime"
  unit_of_measurement: 'days'
  icon: mdi:timer
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/aviv-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

  
# Aviv - HomeAssistant
  
- platform: mqtt
  name: "HomeAssistantPC - HDD Usage (C)"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/hard-drive/c/drive-usage"
  unit_of_measurement: '%'
  icon: mdi:chart-donut
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "HomeAssistantPC - CPU Usage"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/cpu/usage"
  unit_of_measurement: '%'
  icon: mdi:speedometer
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "HomeAssistantPC - RAM Usage"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/memory/usage"
  unit_of_measurement: '%'
  icon: mdi:memory
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
  
- platform: mqtt
  name: "HomeAssistantPC - Remaining Battery"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/battery/remaining-percent"
  unit_of_measurement: '%'
  device_class: battery
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
  
- platform: mqtt
  name: "HomeAssistantPC - Network IPv4"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/network/0/ipv4"
  unit_of_measurement: ''
  icon: mdi:lan
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
  
- platform: mqtt
  name: "HomeAssistantPC - Network IPv6"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/network/0/ipv6"
  unit_of_measurement: ''
  icon: mdi:lan
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
  
- platform: mqtt
  name: "HomeAssistantPC - Up Time"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/system/uptime"
  unit_of_measurement: 'days'
  icon: mdi:timer
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "HomeAssistantPC - Remaining Battery Time"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/battery/remaining-time"
  unit_of_measurement: 'minutes'
  icon: mdi:timer
  value_template: "{{ ( value | float / 60 ) | int }}"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1