- platform: template
  sensors:
    terrace_irrigation_liters_summary:
      friendly_name: "Terrace Irrigation Weight Summary"
      value_template: >-
        {% if is_state('sensor.terrace_irrigation_liters', 'unknown') %}
          Unknown
        {% elif (states('sensor.terrace_irrigation_liters') | float) >= 35 %}
          5
        {% elif ((states('sensor.terrace_irrigation_liters') | float) >= 28) and ((states('sensor.terrace_irrigation_liters') | float) < 35) %}
          4
        {% elif ((states('sensor.terrace_irrigation_liters') | float) >= 21) and ((states('sensor.terrace_irrigation_liters') | float) < 28) %}
          3
        {% elif ((states('sensor.terrace_irrigation_liters') | float) >= 14) and ((states('sensor.terrace_irrigation_liters') | float) < 21) %}
          2
        {% elif ((states('sensor.terrace_irrigation_liters') | float) >= 7) and ((states('sensor.terrace_irrigation_liters') | float) < 14) %}
          1
        {% elif ((states('sensor.terrace_irrigation_liters') | float) >= 0) and ((states('sensor.terrace_irrigation_liters') | float) < 7) %}
          0
        {% else %}
          Failed
        {% endif %}