- platform: template
  sensors:
    bedroom_bedside_lights_mode:
      friendly_name: "Bedroom Bedside Lights Mode"
      icon_template: mdi:heart
      value_template: >-
        {% if is_state('light.bedroom_bedside_yeelight_aviv', 'unavailable') or is_state('light.bedroom_bedside_yeelight_michal', 'unavailable') %}
            unavailable
        {% elif is_state('light.bedroom_bedside_yeelight_aviv', 'off') and is_state('light.bedroom_bedside_yeelight_michal', 'off') %}
            lights_off
        {% elif ( state_attr('light.bedroom_bedside_yeelight_aviv', 'brightness') < 30 ) or ( state_attr('light.bedroom_bedside_yeelight_michal', 'brightness') < 30 ) %}
            romantic
        {% elif ( state_attr('light.bedroom_bedside_yeelight_aviv', 'brightness') >= 30 ) or ( state_attr('light.bedroom_bedside_yeelight_michal', 'brightness') >= 30 ) %}
            normal
        {% else %}
            other
        {% endif %}
