
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include_dir_merge_list automation/
script: !include_dir_merge_named /config/entities/scripts/
scene: !include_dir_merge_list /config/entities/scenes/
sensor: !include_dir_merge_list /config/entities/sensors/
switch: !include_dir_merge_list /config/entities/switches/
rest: !include_dir_merge_list /config/entities/rests/
binary_sensor: !include_dir_merge_list /config/entities/binary_sensors/
zone: !include /config/entities/zones.yaml
group: !include_dir_merge_named group
yeelight: !include /config/entities/yeelights.yaml
plant: !include /config/entities/plants.yaml
utility_meter: !include /config/entities/utility_meter.yaml

frontend:
  themes: !include_dir_merge_named themes

homekit:
  filter:
    include_domains:
      - switch
      - script
      - sensor
      - climate
      - binary_sensor
ios:

cloud:

wake_on_lan:

logger:
  default: debug

apple_tv:
  - host: !secret host_apple_tv
    login_id: LOGIN_ID_1
    name: AppleTV- LivingRoom
    start_off: false

tplink:
  discovery: false
  switch:
    - host: 192.168.2.48

# Sensibo
climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key
    
# HomeAssistant
homeassistant:
  customize: !include_dir_merge_named customize
#  whitelist_external_dirs: 
# - /config/snapshots

# SpeedTest
speedtestdotnet:
  server_id: 21197
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# Telegram
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id_1

notify:
  - name: AvivTelegram
    platform: telegram
    chat_id: !secret telegram_bot_chat_id_1
    
# DarkSky
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    
# Nmap
device_tracker:
  - platform: nmap_tracker
    hosts: 
      192.168.2.11
      192.168.2.12
      192.168.2.61
      192.168.2.63
      192.168.2.15
      192.168.2.16
      192.168.2.17
      192.168.2.18
      192.168.2.19
      192.168.2.20
      192.168.2.21
      192.168.2.22
      192.168.2.41
      192.168.2.54
      
#switcher_kis:
#  phone_id: '0000'
#  device_id: '1bd21f'
#  device_password: '00000000'

# switcher_kis:
# phone_id: '0000'
# device_id: 'dbc31f'
# device_password: '00000000'

# Sonoff
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  reload: always
  
# Recorder
recorder:
  purge_interval: 1
  purge_keep_days: 3
  include:
    domains:
      - switch
      - sensor
      - device_tracker
      - input_number
      - input_boolean
      - script
      - climate
      - binary_sensor
  exclude:
    domains:
      - automation
      - updater
      - docker_monitor
      - image_processing
    entities:
      - sun.sun
      - sensor.date
      - sensor.dark_sky_daily_summary
      - sensor.dark
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop      
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync
      - panels_updated
      - persistent_notifications_updated
      - config_entry_discovered
      
#MQTT
# mqtt:
  # broker: !secret mqtt_broker
  # username: !secret mqtt_username
  # password: !secret mqtt_password

# Cameras      
camera:
- platform: generic
  name: Weather
  still_image_url: !secret weather_still_image_url
  content_type: 'image/svg+xml'
- platform: mjpeg
  mjpeg_url: !secret blueiris_kitchen_mjpg_address
  name: Kitchen Blueiris Camera
  username: !secret blueiris_username
  password: !secret blueiris_password
  authentication: basic
- platform: mjpeg
  mjpeg_url: !secret blueiris_livingroom_mjpg_address
  name: LivingRoom Blueiris Camera
  username: !secret blueiris_username
  password: !secret blueiris_password
  authentication: basic
- platform: mjpeg
  mjpeg_url: !secret blueiris_entrance_mjpg_address
  name: Entrance Blueiris Camera
  username: !secret blueiris_username
  password: !secret blueiris_password
  authentication: basic