- platform: template
  switches:
    switcher_webapi_bottom_top_rig_ac:
        friendly_name: Switcher Bottom Top Rig AC
        icon_template: mdi:power
        entity_id: sensor.switcher_webapi_bottom_top_rig_ac
        value_template: "{{ is_state_attr('sensor.switcher_webapi_bottom_top_rig_ac', 'state', 'on') }}"
        turn_on:
            service: script.turn_on
            data:
              entity_id: script.switcher_turn_on
        turn_off:
            service: script.turn_on
            data:
              entity_id: script.switcher_turn_of
              
    switcher_webapi_top_rig:
        friendly_name: Switcher Top Rig
        icon_template: mdi:power
        entity_id: sensor.switcher_webapi_top_rig
        value_template: "{{ is_state_attr('sensor.switcher_webapi_top_rig', 'state', 'on') }}"
        turn_on:
            service: script.turn_on
            data:
              entity_id: script.switcher_turn_on
        turn_off:
            service: script.turn_on
            data:
              entity_id: script.switcher_turn_of