- platform: template
  switches:
    bedroom_bedside_romantic_light_toggle:
        friendly_name: Bedroom Bedside Romantic Light Toggle
        icon_template: mdi:brightness-4
        value_template: "{{ is_state('sensor.bedroom_bedside_lights_mode', 'romantic') }}"
        turn_on:
            service: scene.turn_on
            data:
                entity_id: scene.bedroom_bedside_romantic 
        turn_off:
            service: scene.turn_on
            data:
                entity_id: scene.bedroom_bedside_normal                    

    bedroom_bedside_romantic_light:
        friendly_name: Bedroom Bedside Romantic Light
        icon_template: mdi:led-strip-variant
        value_template: "{{ is_state('sensor.bedroom_bedside_lights_mode', 'romantic') }}"
        turn_on:
            service: scene.turn_on
            data:
                entity_id: scene.bedroom_bedside_romantic 
        turn_off:
            service: scene.turn_on
            data:
                entity_id: scene.bedroom_bedside_off

    bedroom_bedside_normal_light:
        friendly_name: Bedroom Bedside Normal Light
        icon_template: mdi:led-strip-variant
        value_template: "{{ is_state('sensor.bedroom_bedside_lights_mode', 'normal') }}"
        turn_on:
            service: scene.turn_on
            data:
                entity_id: scene.bedroom_bedside_normal 
        turn_off:
            service: scene.turn_on
            data:
                entity_id: scene.bedroom_bedside_off
