# IOT Link
- platform: mqtt
  name: "AvivPC - Connected"
  state_topic: "iotlink/workgroup/aviv-pc/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1
  
- platform: mqtt
  name: "HomeAssistantPC - Connected"
  state_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1
  
- platform: mqtt
  name: "HomeAssistantPC - Plugged"
  state_topic: "iotlink/workgroup/desktop-32dlq86/windows-monitor/stats/power/status"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "plug"
  availability_topic: "iotlink/workgroup/desktop-32dlq86/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1